"""add_tyco_student_roll_call_fields

Revision ID: 649a55de0973
Revises: aada8bbb832d
Create Date: 2026-10-07 23:40:17.068140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649a55de0973'
down_revision = 'aada8bbb832d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sr_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zprn', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('student_contact', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('parent_contact_1', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('parent_contact_2', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('division', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('batch', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('class_name', sa.String(length=50), nullable=True))
        batch_op.alter_column('roll_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_students_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_zprn'), ['zprn'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_zprn'))
        batch_op.drop_index(batch_op.f('ix_students_name'))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('roll_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('class_name')
        batch_op.drop_column('batch')
        batch_op.drop_column('division')
        batch_op.drop_column('parent_contact_2')
        batch_op.drop_column('parent_contact_1')
        batch_op.drop_column('student_contact')
        batch_op.drop_column('name')
        batch_op.drop_column('zprn')
        batch_op.drop_column('sr_no')

    # ### end Alembic commands ###
