"""Initial database schema

Revision ID: aada8bbb832d
Revises: 
Create Date: 2026-10-07 20:10:41.584167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aada8bbb832d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=30), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('columns_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_room_number'), ['room_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=30), nullable=False),
    sa.Column('row_num', sa.Integer(), nullable=False),
    sa.Column('col_num', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'row_num', 'col_num', name='uq_room_row_col'),
    sa.UniqueConstraint('room_id', 'seat_number', name='uq_room_seat_number')
    )
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seats_room_id'), ['room_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('enrollment_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_enrollment_number'), ['enrollment_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_subjects_department_id'), ['department_id'], unique=False)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('max_duties_per_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=True)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('session_name', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_registered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_exam_code'), ['exam_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_exams_exam_date'), ['exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_subject_id'), ['subject_id'], unique=False)

    op.create_table('invigilation_duties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('duty_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'teacher_id', name='uq_teacher_exam_duty')
    )
    with op.batch_alter_table('invigilation_duties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invigilation_duties_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invigilation_duties_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invigilation_duties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invigilation_duties_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'exam_id', name='uq_student_exam_registration')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_student_id'), ['student_id'], unique=False)

    op.create_table('seating_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_students_allocated', sa.Integer(), nullable=False),
    sa.Column('total_rooms_used', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seating_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seating_plans_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seating_plans_plan_code'), ['plan_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_seating_plans_status'), ['status'], unique=False)

    op.create_table('teacher_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=30), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_availabilities_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_availabilities_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_availabilities_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('duty_swaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_teacher_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['duty_id'], ['invigilation_duties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duty_swaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_swaps_duty_id'), ['duty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_swaps_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_swaps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_swaps_target_teacher_id'), ['target_teacher_id'], unique=False)

    op.create_table('seat_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seating_plan_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seating_plan_id'], ['seating_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seating_plan_id', 'seat_id', name='uq_plan_seat_allocation'),
    sa.UniqueConstraint('seating_plan_id', 'student_id', name='uq_plan_student_allocation')
    )
    with op.batch_alter_table('seat_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_allocations_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_seat_id'), ['seat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_seating_plan_id'), ['seating_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_allocations_student_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_seating_plan_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_seat_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_room_id'))

    op.drop_table('seat_allocations')
    with op.batch_alter_table('duty_swaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_swaps_target_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_duty_swaps_status'))
        batch_op.drop_index(batch_op.f('ix_duty_swaps_requester_id'))
        batch_op.drop_index(batch_op.f('ix_duty_swaps_duty_id'))

    op.drop_table('duty_swaps')
    with op.batch_alter_table('teacher_availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_availabilities_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_availabilities_exam_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_availabilities_date'))

    op.drop_table('teacher_availabilities')
    with op.batch_alter_table('seating_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seating_plans_status'))
        batch_op.drop_index(batch_op.f('ix_seating_plans_plan_code'))
        batch_op.drop_index(batch_op.f('ix_seating_plans_exam_id'))

    op.drop_table('seating_plans')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_student_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_exam_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('invigilation_duties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invigilation_duties_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_invigilation_duties_status'))
        batch_op.drop_index(batch_op.f('ix_invigilation_duties_room_id'))
        batch_op.drop_index(batch_op.f('ix_invigilation_duties_exam_id'))

    op.drop_table('invigilation_duties')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_subject_id'))
        batch_op.drop_index(batch_op.f('ix_exams_status'))
        batch_op.drop_index(batch_op.f('ix_exams_exam_date'))
        batch_op.drop_index(batch_op.f('ix_exams_exam_code'))

    op.drop_table('exams')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_employee_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_department_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_department_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))
        batch_op.drop_index(batch_op.f('ix_students_enrollment_number'))
        batch_op.drop_index(batch_op.f('ix_students_department_id'))

    op.drop_table('students')
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seats_room_id'))

    op.drop_table('seats')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_room_number'))

    op.drop_table('rooms')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
